# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050



  peer0.CrabAssociation.com:
    container_name: peer0.CrabAssociation.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.CrabAssociation.com
      - CORE_PEER_ADDRESS=peer0.CrabAssociation.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.CrabAssociation.com:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CrabAssociation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CrabAssociation.com:7051
      - CORE_PEER_LOCALMSPID=CrabAssociationMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CrabAssociation.com/peers/peer0.CrabAssociation.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CrabAssociation.com/peers/peer0.CrabAssociation.com/tls:/etc/hyperledger/fabric/tls
        - peer0.CrabAssociation.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053










  peer0.CrabProducer.com:
    container_name: peer0.CrabProducer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.CrabProducer.com
      - CORE_PEER_ADDRESS=peer0.CrabProducer.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_CHAINCODEADDRESS=peer0.CrabProducer.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CrabProducer.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CrabProducer.com:8051
      - CORE_PEER_LOCALMSPID=CrabProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CrabProducer.com/peers/peer0.CrabProducer.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CrabProducer.com/peers/peer0.CrabProducer.com/tls:/etc/hyperledger/fabric/tls
        - peer0.CrabProducer.com:/var/hyperledger/production

    ports:
      - 8051:8051
      - 8053:8053



  peer0.CrabCarrier.com:
    container_name: peer0.CrabCarrier.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.CrabCarrier.com
      - CORE_PEER_ADDRESS=peer0.CrabCarrier.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.CrabCarrier.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CrabCarrier.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CrabCarrier.com:9051
      - CORE_PEER_LOCALMSPID=CrabCarrierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CrabCarrier.com/peers/peer0.CrabCarrier.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CrabCarrier.com/peers/peer0.CrabCarrier.com/tls:/etc/hyperledger/fabric/tls
        - peer0.CrabCarrier.com:/var/hyperledger/production

    ports:
      - 9051:9051
      - 9053:9053



  peer0.CrabSeller.com:
    container_name: peer0.CrabSeller.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.CrabSeller.com
      - CORE_PEER_ADDRESS=peer0.CrabSeller.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.CrabSeller.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:10053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CrabSeller.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.CrabSeller.com:10051
      - CORE_PEER_LOCALMSPID=CrabSellerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/CrabSeller.com/peers/peer0.CrabSeller.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/CrabSeller.com/peers/peer0.CrabSeller.com/tls:/etc/hyperledger/fabric/tls
        - peer0.CrabSeller.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

